### ISSUE TITLE
Why was I banned from the Discord server?

### ISSUE THREAD

**Issue by bachimusprime** [PSI-Rockin/Corgi3DS#5]
I had done NOTHING wrong in that server, and hell, you didn't ban @Cyuubi who was PURPOSEFULLY shit-stirring, so why was I banned? And why the fuck do you two hate me so goddamned much? Just give me a good reason, and I will stop bugging you.

**Comment by PSI-Rockin** [comment]
Closing this as it's not a real issue. Please use the issue tracker to report bugs only.

**Comment by dd01da0465b4542f8f8af4ecedc149ed** [comment]
How about you stop being a pedophile, thanks.
